--- description: demo rum data
--- Authorization: none
--- Access-Control-Allow-Origin: *
--- offset: 0
--- repo: express-website

SELECT
  COUNT(*) AS URLHITS,
  AVG(LCP) AS AVGLCP,
  AVG(FID) AS AVGFID,
  AVG(CLS) AS AVGCLS,
  EXTRACT(MONTH FROM TIMESTAMP_MILLIS(CAST(TIME AS int64))) AS MONTH,
  EXTRACT(DAY FROM TIMESTAMP_MILLIS(CAST(TIME AS int64))) AS DAY,
  EXTRACT(YEAR FROM TIMESTAMP_MILLIS(CAST(TIME AS int64))) AS YEAR
FROM `helix-225321.helix_rum.rum20*`
WHERE URL IS NOT NULL
  AND CONTAINS_SUBSTR(URL, @repo)
GROUP BY MONTH, DAY, YEAR
HAVING AVGLCP IS NOT NULL
  AND AVGFID IS NOT NULL
  AND AVGCLS IS NOT NULL
ORDER BY YEAR ASC, MONTH ASC, DAY ASC
