name: SQLFluff Lint

on:
  - pull_request

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.13"
      - name: install sqlfluff
        run: "pip install sqlfluff"
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            src/queries/**/*.sql
          files_ignore: |
            **/common*.sql
      - name: Get changed .sql files in /src/queries to lint
        id: get_files_to_lint
        run: |
          LINTEES="${{ steps.changed-files.outputs.all_changed_files }}"
          echo "lintees=${LINTEES}" >> $GITHUB_OUTPUT
      - name: Lint dbt models
        id: sqlfluff_json
        if: steps.get_files_to_lint.outputs.lintees != ''
        run: sqlfluff lint --format github-annotation --annotation-level failure --nofail ${{ steps.get_files_to_lint.outputs.lintees }} > annotations.json
      - name: Annotate
        uses: yuzutech/annotations-action@v0.5.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: "SQLFluff Lint"
          input: "./annotations.json"
